import type { ArtifactContent } from "./artifact-schemas";

export function renderMarkdown(content: ArtifactContent): string {
  const lines: string[] = [];
  lines.push(`# ${content.title}`);
  if (content.subtitle) lines.push(`\n_${content.subtitle}_\n`);

  if (content.metrics && content.metrics.length) {
    lines.push("\n## Headline Metrics\n");
    lines.push("| Metric | Value | Notes |");
    lines.push("|---|---|---|");
    for (const m of content.metrics) {
      lines.push(`| ${m.label} | ${m.value} | ${m.subtext ?? ""} |`);
    }
  }

  for (const s of content.sections) {
    lines.push(`\n## ${s.heading}\n`);
    lines.push(s.content);
  }

  if (content.nextSteps && content.nextSteps.length) {
    lines.push("\n## Recommended Next Steps\n");
    for (const n of content.nextSteps) lines.push(`- ${n}`);
  }

  if (content.assumptions && content.assumptions.length) {
    lines.push("\n## Assumptions and Inputs Used\n");
    for (const a of content.assumptions) lines.push(`- ${a}`);
  }

  lines.push(
    "\n---\n\n_Generated by Workshop Buddy. AI-drafted content; human review and approval required before client use._\n"
  );
  return lines.join("\n");
}
